#ifndef SHARE_CONSTANTS_H_INCLUDED
#define SHARE_CONSTANTS_H_INCLUDED

#define MAX_TEXTURE_COUNT (512)

#define BASE_COLOUR_MAP_BIT (1 << 0)
#define EMISSION_MAP_BIT (1 << 1)
#define ROUGHNESS_MAP_BIT (1 << 2)
#define METALNESS_MAP_BIT (1 << 3)
#define ROUGHNESS_METALNESS_MAP_BIT (1 << 4)
#define SPECULAR_MAP_BIT (1 << 5)
#define SPECULAR_TINT_MAP_BIT (1 << 6)
#define SHEEN_MAP_BIT (1 << 7)
#define SHEEN_TINT_MAP_BIT (1 << 8)
#define CLEARCOAT_MAP_BIT (1 << 9)
#define CLEARCOAT_ROUGHNESS_MAP_BIT (1 << 10)
#define ANISOTROPY_MAP_BIT (1 << 11)
#define NORMAL_MAP_BIT (1 << 12)

#define LIGHT_TYPE_POINT (1)
#define LIGHT_TYPE_DIRECTIONAL (2)
#define LIGHT_TYPE_EMITTER (3)

#define NO_EMITTER_INDEX (4294967295U)

#define LIGHT_BIN_SIZE (10)
#define EMITTER_BIN_SIZE (6)

#define PTRESET_GROUP_SIZE (16)
#define TONE_MAP_GROUP_SIZE (16)

#define QUEUE_ITEM_SIZE (16)
#define QUEUE_METADATA_SIZE (2)
#define QUEUE_STRIDE(capacity) ((capacity) * QUEUE_ITEM_SIZE + 1)
#define QUEUE_OFFSET(capacity, queue) (QUEUE_METADATA_SIZE + QUEUE_STRIDE(capacity) * (queue))

#endif